//
//  LOStringHeaderHelp.h
//  YM
//
//  Created by t2 on 15/3/23.
//  Copyright (c) 2015年 YM. All rights reserved.
//

#ifndef YM_LOStringHeaderHelp_h
#define YM_LOStringHeaderHelp_h

#import "ResourceManager.h"

#define LOLocalizedString(KEY,COMMENT) NSLocalizedString(KEY,COMMENT)
#define LOLoadSourceString(MODEL,KEY) [[ResourceManager shareManager] resourStrforModel:MODEL andKey:KEY]


//0 消息 1 通讯录 2 探索 3 我 4 公用 5 登录注册

#define NET_ERROR_CODE   1000 //wang
#define NET_ERROR_FAILD   NET_ERROR_CODE+1
#define NET_ERROR         LOLocalizedString(@"发生一个未知的错误!",nil)
#define NET_TIMEOUT       LOLocalizedString(@"网络异常,请检查您的网络!", nil)

//0 消息
#define group_exitalarm             LOLoadSourceString(0,@"group_exitalarm")        //确定退出该群？
#define group_dissolvealarm         LOLoadSourceString(0,@"group_dissolvealarm")    //确定要解散该群？
#define chat_record                 LOLoadSourceString(0,@"chat_record")            //聊天记录
#define string_location             LOLoadSourceString(0,@"string_location")        //位置
#define string_send                 LOLoadSourceString(0,@"string_send")            //发送
#define is_locationing              LOLoadSourceString(0,@"is_locationing")         //正在定位...
#define string_addressbook          LOLoadSourceString(0,@"string_addressbook")     //通讯录
#define alert_send_photo            LOLoadSourceString(0,@"alert_send_photo")       //确定需要发送该图片吗?
#define now_chat_log                LOLoadSourceString(0,@"now_chat_log")           //当前聊天记录
#define del_and_logout_group        LOLoadSourceString(0,@"del_and_logout_group")   //删除并退群
#define dissolution_group           LOLoadSourceString(0,@"dissolution_group")      //解散该群
#define group_message_setting       LOLoadSourceString(0,@"group_message_setting")  //群消息设置
#define group_chat_header           LOLoadSourceString(0,@"group_chat_header")      //群聊头像
#define group_chat_name             LOLoadSourceString(0,@"group_chat_name")        //群聊名称
#define save_to_contact             LOLoadSourceString(0,@"save_to_contact")        //保存到通讯录
#define to_top_chat                 LOLoadSourceString(0,@"to_top_chat")            //置顶聊天
#define accept_not_prompt           LOLoadSourceString(0,@"accept_not_prompt")      //接收消息不提示
#define clear_all_chat_log          LOLoadSourceString(0,@"clear_all_chat_log")     //清空聊天内容
#define getting_message             LOLoadSourceString(0,@"getting_message")        //正在获取信息...
#define change_chat_group_name      LOLoadSourceString(0,@"change_chat_group_name") //%@修改了群名称
#define change_chat_group_header    LOLoadSourceString(0,@"change_chat_group_header")//%@修改了群头像
#define share_card                  LOLoadSourceString(0,@"share_card")             //分享名片
#define alert_share_master_to       LOLoadSourceString(0,@"alert_share_master_to")  //确定分享我的达人统计给%@?
#define alert_share_card_to         LOLoadSourceString(0,@"alert_share_card_to")    //确定分享%@的名片给%@?
#define voice_not_began             LOLoadSourceString(0,@"voice_not_began")        //录音没有开始
#define voice_too_short             LOLoadSourceString(0,@"voice_too_short")        //录音时间过短
#define string_card                 LOLoadSourceString(0,@"string_card")            //名片
#define create_group_chat           LOLoadSourceString(0,@"create_group_chat")      //发起群聊
#define add_new_friend              LOLoadSourceString(0,@"add_new_friend")         //添加朋友
#define string_scan_scan            LOLoadSourceString(0,@"string_scan_scan")       //扫一扫
#define whose_group                 LOLoadSourceString(0,@"whose_group")            //的群
#define message_setting             LOLoadSourceString(0,@"message_setting")        //消息设置
#define del_with_one_chat_log       LOLoadSourceString(0,@"del_with_one_chat_log")  //删除和%@的聊天记录
#define string_picture              LOLoadSourceString(0,@"string_picture")         //照片
#define string_shot                 LOLoadSourceString(0,@"string_shot")            //拍摄
#define cancel_voice_send           LOLoadSourceString(0,@"cancel_voice_send")      //手指向上滑,取消发送
#define cancel_voice_send_touch     LOLoadSourceString(0,@"cancel_voice_send_touch")//松开手指,取消发送
#define send_success                LOLoadSourceString(0,@"send_success")           //发送成功
#define send_picture_to             LOLoadSourceString(0,@"send_picture_to")        //确定需要发送图片给%@吗?
#define message_title               LOLoadSourceString(0,@"message_title")          //消息


//1 通讯录
#define phone_marching_user         LOLoadSourceString(1,@"phonemarch")             //输入的号码与如下用户匹配
#define save_and_add                LOLoadSourceString(1,@"save_and_add")           //存储为联系人并申请加为好友
#define new_card                    LOLoadSourceString(1,@"new_card")               //新的名片
#define group_s                     LOLoadSourceString(1,@"group_s")                //群发短信
#define contact_sf                  LOLoadSourceString(1,@"contact_sf")             //联系人
#define select_contact              LOLoadSourceString(1,@"sel_contact")            //选择联系人
#define fdyn_s                      LOLoadSourceString(1,@"fdyn_s")                 //好友动态
#define fback_s                     LOLoadSourceString(1,@"fback_s")                //黑名单
#define group_chat                  LOLoadSourceString(1,@"group_chat")             //群聊
#define fbirs_s                     LOLoadSourceString(1,@"fbirs_s")                //生日提醒
#define fymex_s                     LOLoadSourceString(1,@"fymex_s")                //达人统计
#define contacts_not_list           LOLoadSourceString(1,@"not_contact")            //暂无联系人,请上传联系人
#define birday_not_set              LOLoadSourceString(1,@"birday_not_set")         //没有对好友设置生日提醒
#define load_contacts               LOLoadSourceString(1,@"load_contacts")          //加载通讯录
#define count_contact               LOLoadSourceString(1,@"count_contact")          //共%ld位联系人
#define sear_result                 LOLoadSourceString(1,@"sear_result")            //搜索的结果是
#define search_s                    LOLoadSourceString(1,@"sear")                   //搜索
#define search_phone_c_name         LOLoadSourceString(1,@"sear_phone_name")        //请输入手机号码/姓名/职位/公司
#define sfriend_count               LOLoadSourceString(1,@"sfriend_count")          //%ld个共同好友
#define card_share                  LOLoadSourceString(1,@"card_share")             //名片分享
#define no_message                  LOLoadSourceString(1,@"no_message")             //该设备没有发送短信的功能~
#define low_appversion              LOLoadSourceString(1,@"low_appversion")         //iOS版本过低(iOS4.0以后)
#define authority_camera            LOLoadSourceString(1,@"authority_camera")       //设备没有开启相机服务,请到设置->隐私中开启
#define no_camera                   LOLoadSourceString(1,@"no_camera")              //你没有摄像头
#define authority_photo             LOLoadSourceString(1,@"authority_photo")        //设备没有开启照片服务,请到设置->隐私中开启中开启
#define authority_addressbook       LOLoadSourceString(1,@"authority_addressbook")  //未获得通讯录访问权限
#define dial                        LOLoadSourceString(1,@"dial")                   //拨号
#define new_contact                 LOLoadSourceString(1,@"new_contact")            //新建联系人
#define add_contact                 LOLoadSourceString(1,@"add_contact")            //新增联系人
#define alert_clear_recording       LOLoadSourceString(1,@"alert_clear_recording")  //确定要将通话记录全部清空吗?
#define alert_clear_one_recording   LOLoadSourceString(1,@"alert_clear_one_recording")  //确定要将与此人的通话记录全部清空吗?
#define cp_is_empty                 LOLoadSourceString(1,@"cp_is_empty")            //公司、职位未填写
#define backname                    LOLoadSourceString(1,@"backname")               //备注名
#define call_history                LOLoadSourceString(1,@"call_history")           //通话历史
#define friend_rec                  LOLoadSourceString(1,@"friend_rec")             //推荐好友
#define button_change_a_batch       LOLoadSourceString(1,@"button_change_a_batch")  //换一批
#define black_list                  LOLoadSourceString(1,@"black_list")             //黑名单
#define black_list_content          LOLoadSourceString(1,@"black_list_content")     //黑名单中的用户将无法向您发送消息、换名片申请、也无法对您进行评论、贴标签等操作
#define change_binding_tel          LOLoadSourceString(1,@"change_binding_tel")     //更改了绑定电话
#define change_company              LOLoadSourceString(1,@"change_company")         //更改了公司
#define change_position             LOLoadSourceString(1,@"change_position")        //更改了职位
#define state_add_remarks_tel       LOLoadSourceString(1,@"state_add_remarks_tel")  //添加了备注电话
#define change_birthday             LOLoadSourceString(1,@"change_birthday")        //更改了生日
#define change_education            LOLoadSourceString(1,@"change_education")       //更改了教育信息
#define birthday_details            LOLoadSourceString(1,@"birthday_details")       //生日详细
#define add_remark_tel              LOLoadSourceString(1,@"add_remark_tel")         //添加备注电话
#define add_new_contact_tel         LOLoadSourceString(1,@"add_new_contact_tel")    //添加新的联系电话
#define input_new_tel               LOLoadSourceString(1,@"input_new_tel")          //请输入新号码
#define alert_equal_data            LOLoadSourceString(1,@"alert_equal_data")       //已存在相同的数据
#define toast_max_remark_tel        LOLoadSourceString(1,@"toast_max_remark_tel")   //最多只能添加%ld条备注电话
#define alert_back                  LOLoadSourceString(1,@"alert_back")             //本次修改未保存是否确定返回
#define new_group                   LOLoadSourceString(1,@"new_group")              //新分组
#define give_TA_new_grop            LOLoadSourceString(1,@"give_TA_new_grop")       //给TA添加分组
#define group_of                    LOLoadSourceString(1,@"group_of")               //%@所在的分组
#define other_groups                LOLoadSourceString(1,@"other_groups")           //可选其它分组
#define share_by_app                LOLoadSourceString(1,@"share_by_app")           //来自%@的名片分享
#define share_to_weixin             LOLoadSourceString(1,@"share_to_weixin")        //分享名片到微信
#define details                     LOLoadSourceString(1,@"details")                //详细资料
#define user_details                LOLoadSourceString(1,@"user_details")           //用户资料
#define cancel_star_mark            LOLoadSourceString(1,@"cancel_star_mark")       //取消星标
#define add_star_mark               LOLoadSourceString(1,@"add_star_mark")          //添加星标
#define cancel_black                LOLoadSourceString(1,@"cancel_black")           //解除黑名单
#define add_black                   LOLoadSourceString(1,@"add_black")              //加入黑名单
#define edit_contacts               LOLoadSourceString(1,@"edit_contacts")          //编辑联系人
#define share_contacts              LOLoadSourceString(1,@"share_contacts")         //分享联系人
#define add_to_iphone               LOLoadSourceString(1,@"add_to_iphone")          //添加到手机
#define del_by_app                  LOLoadSourceString(1,@"del_by_app")             //删除联系人
#define alert_add_to_iphone         LOLoadSourceString(1,@"alert_add_to_iphone")    //是否将他的联系方式添加到手机通讯录中
#define share_by_the_way            LOLoadSourceString(1,@"share_by_the_way")       //通过以下方式分享该联系人
#define alert_can_add_by_black      LOLoadSourceString(1,@"alert_can_add_by_black") //对方已不再黑名单中,可以添加为好友了
#define alert_del_black_fail        LOLoadSourceString(1,@"alert_del_black_fail")   //解除失败
#define alert_add_black             LOLoadSourceString(1,@"alert_add_black")        //是否将 %@ 加入黑名单
#define alert_is_del                LOLoadSourceString(1,@"alert_is_del")           //是否删除 %@
#define add_tel_type                LOLoadSourceString(1,@"add_tel_type")           //添加电话标签
#define alert_teltype_count         LOLoadSourceString(1,@"alert_teltype_count")    //类别不能超过2个字
#define alert_teltype_not_empty     LOLoadSourceString(1,@"alert_teltype_count")    //类别不能为空
#define string_sfriend              LOLoadSourceString(1,@"string_sfriend")         //共同好友
#define contact_sfriend_count       LOLoadSourceString(1,@"contact_sfriend_count")  //%ld人也把TA标记为好友
#define recommended_notes           LOLoadSourceString(1,@"recommended_notes")      //推荐备注
#define recommended_count           LOLoadSourceString(1,@"recommended_count")      //%@人对TA的备注
#define bakname_can_not_empty       LOLoadSourceString(1,@"bakname_can_not_empty")  //备注名不能为空
#define toast_max_email_count       LOLoadSourceString(1,@"toast_max_email_count")  //邮箱字数不能超过%d
#define toast_max_weixin_count      LOLoadSourceString(1,@"toast_max_weixin_count") //微信字数不能超过%d
#define toast_max_qq_count          LOLoadSourceString(1,@"toast_max_qq_count")     //QQ字数不能超过%d
#define select_position             LOLoadSourceString(1,@"select_position")        //选择职位
#define select_education            LOLoadSourceString(1,@"select_education")       //选择学历
#define select_profession           LOLoadSourceString(1,@"select_profession")      //选择学院
#define search_company              LOLoadSourceString(1,@"search_company")         //搜索公司
#define input_school                LOLoadSourceString(1,@"input_school")           //输入学校名称
#define input_company               LOLoadSourceString(1,@"input_company")          //输入公司名称

#define search_school               LOLoadSourceString(1,@"search_school")          //搜索学校
#define search_profrssion           LOLoadSourceString(1,@"search_profrssion")      //输入学院名称
#define profession_name           LOLoadSourceString(1,@"profession_name")          //学院名称
#define sfriend_info                LOLoadSourceString(1,@"sfriend_info")           //%@、%@等%ld人
#define add_remark                  LOLoadSourceString(1,@"add_remark")             //点击此处进行备忘
#define toast_add_success           LOLoadSourceString(1,@"toast_add_success")      //添加成功
#define toast_label_repeat          LOLoadSourceString(1,@"toast_label_repeat")     //标签重复
#define send_message                LOLoadSourceString(1,@"send_message")           //免费消息
#define send_shortMessage           LOLoadSourceString(1,@"send_shortMessage")      //发送短信
#define string_invite               LOLoadSourceString(1,@"string_invite")          //邀请
#define string_invite_regist        LOLoadSourceString(1,@"string_invite_regist")   //邀请注册
#define call_phone                  LOLoadSourceString(1,@"call_phone")             //打电话
#define add_contact_and_friend      LOLoadSourceString(1,@"add_contact_and_friend") //存为联系人并申请加好友 改为 //添加好友
#define add_friend                  LOLoadSourceString(1,@"add_friend")             //添加好友
#define add_to_contact              LOLoadSourceString(1,@"add_to_contact")         //添加到通讯录
#define request_friend_success      LOLoadSourceString(1,@"request_friend_success") //好友请求发送成功
#define choose_group                LOLoadSourceString(1,@"choose_group")           //点击选择分组
#define add_black_success           LOLoadSourceString(1,@"add_black_success")      //黑名单添加成功
#define del_success                 LOLoadSourceString(1,@"del_success")            //删除成功
#define max_add_label_count         LOLoadSourceString(1,@"max_add_label_count")    //最多只能给当前联系人发送%ld条标签
#define max_all_label_count         LOLoadSourceString(1,@"max_all_label_count")    //当前用户标签总数不能超过%ld条
#define alert_input_label_name      LOLoadSourceString(1,@"alert_input_label_name") //请填写标签名
#define group_members               LOLoadSourceString(1,@"group_members")          //分组成员
#define string_group                group_s//LOLoadSourceString(1,@"string_group")           //分组
#define group_name                  LOLoadSourceString(1,@"group_name")             //分组名字
#define so_group_type               LOLoadSourceString(1,@"so_group_type")          //例如家人、朋友、同事
#define group_members_list          LOLoadSourceString(1,@"group_members_list")     //成员列表
#define del_group                   LOLoadSourceString(1,@"del_group")              //删除该分组
#define save_other_group            LOLoadSourceString(1,@"save_other_group")       //另存为新分组
#define group_explain1              LOLoadSourceString(1,@"group_explain1")         //手机短信群发,是以手机短信方式,会正常产生费用
#define group_explain2              LOLoadSourceString(1,@"group_explain2")         //备注了多个号码的联系人,系统默认使用常用号码.可以联系人详情中设置常用号码
#define alert_group_name_length     LOLoadSourceString(1,@"alert_group_name_length")//不能超于18个字
#define group_name_not_empty        LOLoadSourceString(1,@"group_name_not_empty")   //分组名字不能为空
#define alert_del_group             LOLoadSourceString(1,@"alert_del_group")        //分组中的联系人不会被删除,是否删除分组?
#define had_select_contact          LOLoadSourceString(1,@"had_select_contact")      //已选择%ld位好友
#define search_result               LOLoadSourceString(1,@"search_result")           //搜索的结果是:
#define merge_contact               LOLoadSourceString(1,@"merge_contact")           //合并联系人
#define matching_done               LOLoadSourceString(1,@"matching_done")           //匹配完成
#define input_contact_name_tel      LOLoadSourceString(1,@"input_contact_name_tel")  //请输入联系人的姓名和电话
#define name_rule                   LOLoadSourceString(1,@"name_rule")               //姓名不能超过5个汉字或10个字母
#define name_not_empty              LOLoadSourceString(1,@"name_not_empty")          //姓名不能为空
#define number_not_empty            LOLoadSourceString(1,@"number_not_empty")        //号码不能为空
#define number_formate_err          LOLoadSourceString(1,@"number_formate_err")      //号码格式填写错误
#define success_to_new_contact      LOLoadSourceString(1,@"success_to_new_contact")  //生成新联系人成功
#define add_card                    LOLoadSourceString(1,@"add_card")                //添加名片
#define add_card_explain            LOLoadSourceString(1,@"add_card_explain")        //手机号/姓名/职位/公司
#define call_tel_1_weeks            LOLoadSourceString(1,@"call_tel_1_weeks")        //最近一周被拨打%@次
#define call_tel_1_months           LOLoadSourceString(1,@"call_tel_1_months")       //最近一个月被拨打%@次
#define call_tel_1_years            LOLoadSourceString(1,@"call_tel_1_years")        //最近一年被拨打%@次
#define string_visitor              LOLoadSourceString(1,@"string_visitor")          //访客
#define string_friend               LOLoadSourceString(1,@"string_friend")           //好友
#define del_in_his_contact          LOLoadSourceString(1,@"del_in_his_contact")      //在TA的通讯录中删除我
#define unknow_city                 LOLoadSourceString(1,@"unknow_city")             //未知城市
#define string_accept               LOLoadSourceString(1,@"string_accept")           //接受
#define str_firend                  LOLoadSourceString(1,@"str_firend")              //朋友
#define str_recommend               LOLoadSourceString(1,@"str_recommend")           //推荐
#define str_old_bir                 LOLoadSourceString(1,@"str_old_bir")             //后过生日
#define str_ld_bir                  LOLoadSourceString(1,@"str_ld_bir")              //过%lu岁生日
#define str_ld_day                  LOLoadSourceString(1,@"str_ld_day")              //%lu天
#define str_lud_year_bir            LOLoadSourceString(1,@"str_lud_year_bir")        //后过%lu岁生日
#define str_bir_day                 LOLoadSourceString(1,@"str_bir_day")             //天
#define remid_time                  LOLoadSourceString(1,@"remid_time")              //提醒时间
#define remid_three_set             LOLoadSourceString(1,@"remid_three_set")         //您可以设置3个提醒
#define not_remids                  LOLoadSourceString(1,@"not_remids")              //不提醒
#define remids_curr_day             LOLoadSourceString(1,@"remids_curr_day")         //当天
#define ahead_one_day               LOLoadSourceString(1,@"ahead_one_day")           //提前一天
#define ahead_two_day               LOLoadSourceString(1,@"ahead_two_day")           //提前两天
#define ahead_three_day             LOLoadSourceString(1,@"ahead_three_day")         //提前三天
#define ahead_seven_day             LOLoadSourceString(1,@"ahead_seven_day")         //提前七天
#define remid_time_k                LOLoadSourceString(1,@"remid_time_k")            //提醒时刻
#define remid_max_three             LOLoadSourceString(1,@"remid_max_three")         //最多能选择3个提醒
#define edit_remid                  LOLoadSourceString(1,@"edit_remid")              //编辑提醒
#define str_birthday                LOLoadSourceString(1,@"str_birthday")            //生日
#define str_remid_set               LOLoadSourceString(1,@"str_remid_set")           //提醒设置
#define str_create_contact          LOLoadSourceString(1,@"str_create_contact")      //创建联系人
#define str_saveto_contact          LOLoadSourceString(1,@"str_saveto_contact")      //存为已有联系人
#define str_star                    LOLoadSourceString(1,@"str_star")                //星座
#define label_toast                 LOLoadSourceString(1,@"label_toast")             //不能输入标点等字符
#define networking_err              LOLoadSourceString(1,@"network_title")           //未能连接到网络，请检查网络设置
#define group_not_create            LOLoadSourceString(1,@"group_not_create")        //该分组还未创建
#define had_add                     LOLoadSourceString(1,@"had_add")                 //已添加
#define bir_t_alert                 LOLoadSourceString(1,@"bir_t_alert")             //确认要删除该生日提醒?
#define users_regester              LOLoadSourceString(1,@"users_regester")          //注册用户
#define firend_os_firends           LOLoadSourceString(1,@"firend_os_firends")           //好友的好友
#define click_show_all              LOLoadSourceString(1,@"click_show_all")          //点击查看联系人更多信息
#define firend_to_s                 LOLoadSourceString(1,@"firend_to_s")             //好友驾到
#define contact_sec1                LOLoadSourceString(1,@"contact_sec1")            //你有新的好友注册啦，打个招呼吧~
#define you_ta_sfriend              LOLoadSourceString(1,@"you_ta_sfriend")          //你和ta的共同好友
#define label_length_max            LOLoadSourceString(1,@"label_length_max")        //标签长度不能超过10个字
#define out_group_add               LOLoadSourceString(1,@"out_group_add")           //群组数量不能超过%ld个
#define invite_success              LOLoadSourceString(1,@"invite_success")          //邀请发送成功
#define unknow_area                 LOLoadSourceString(1,@"unknow_area")             //未知地区
#define contact_Type_Regiser        LOLoadSourceString(1,@"contact_Type_Regiser")    //注册用户
#define contact_Type_All            LOLoadSourceString(1,@"contact_Type_All")        //所有用户
#define more_info                   LOLoadSourceString(1,@"more_info")               //更多资料
#define all_select                  LOLoadSourceString(1,@"all_select")              //全选
#define all_not_select              LOLoadSourceString(1,@"all_not_select")          //取消全选
#define group_name_repeat           LOLoadSourceString(1,@"group_name_repeat")       //分组名重复
#define phone_ofen                  LOLoadSourceString(1,@"phone_ofen")              //该号码最近常用
#define phone_noOfen                LOLoadSourceString(1,@"phone_noOfen")            //该号码不常使用
#define phone_noData                LOLoadSourceString(1,@"phone_noData")            //该号码暂无数据
#define more_dynamic                LOLoadSourceString(1,@"more_dynamic")            //更多动态
#define string_fax                  LOLoadSourceString(1,@"string_fax")              //传真
#define string_com_address          LOLoadSourceString(1,@"string_com_address")      //网址
#define can_not_see_more_info       LOLoadSourceString(1,@"can_not_see_more_info")   //资料完善度不足%@,暂时不能查看好友更多资料
#define see_to_perfect              LOLoadSourceString(1,@"see_to_perfect")          //完善您的资料后可见
#define out_group_message_count     LOLoadSourceString(1,@"out_group_message_count") //您选择的人数较多，需要分成%ld次发送，首次发送后请回到选择成员界面继续发送。
#define had_no_send_text            LOLoadSourceString(1,@"had_no_send_text")        //短信群发已完成%ld/%ld，继续发送
#define msg_all_send_success        LOLoadSourceString(1,@"msg_all_send_success")    //短信已全部发送成功
#define not_find_tel                LOLoadSourceString(1,@"not_find_tel")            //没有找到有效的手机号码
#define has_not_send_message        LOLoadSourceString(1,@"has_not_send_message")    //当前有群发短信未完成

//2 探索
#define recv_catd_you               LOLoadSourceString(2,@"recv_catd_you")           //没有收到递给你的名片,再试试吧
#define string_circle               LOLoadSourceString(2,@"string_circle")           //我的好友圈
#define string_filter               LOLoadSourceString(2,@"string_filter")           //筛选
#define string_hello                LOLoadSourceString(2,@"string_filter")           //你好
#define only_see_stranger           LOLoadSourceString(2,@"only_see_stranger")       //只看陌生人
#define show_all                    LOLoadSourceString(2,@"show_all")                //显示全部
#define group_for_business_card     LOLoadSourceString(2,@"group_for_business_card") //群换名片
#define received_card               LOLoadSourceString(2,@"received_card")           //收到的名片
#define clear_all                   LOLoadSourceString(2,@"clear_all")               //清空
#define position_empty              LOLoadSourceString(2,@"position_empty")          //职位信息未填写
#define del_all_history_card        LOLoadSourceString(2,@"del_all_history_card")    //是否删除全部历史接收到的名片?
#define string_scan                 LOLoadSourceString(2,@"string_scan")             //扫描二维码
#define string_exploration          LOLoadSourceString(2,@"string_exploration")      //探索
#define group_select_explain        LOLoadSourceString(2,@"group_select_explain")    //选择下列联系人交换联系方式
#define group_change_explain        LOLoadSourceString(2,@"group_change_explain")    //在商务环境中,大家可以通过输入同样的4个数字,来彼此交换电子名片
#define leave_temporary             LOLoadSourceString(2,@"leave_temporary")         //直接退出
#define leave_forever               LOLoadSourceString(2,@"leave_forever")           //清除信息并退出
#define people_nearby               LOLoadSourceString(2,@"people_nearby")           //附近的人
#define within_10_meters            LOLoadSourceString(2,@"within_10_meters")        //10米以内
#define within_50_meters            LOLoadSourceString(2,@"within_50_meters")        //50米以内
#define within_100_meters           LOLoadSourceString(2,@"within_100_meters")       //100米以内
#define within_more_meters          LOLoadSourceString(2,@"within_more_meters")      //%d米内
#define within_kilometers           LOLoadSourceString(2,@"within_kilometers")       //%d.%d公里内
#define within_more_kilometers      LOLoadSourceString(2,@"within_more_kilometers")  //%d公里内
#define minutes_ago                 LOLoadSourceString(2,@"minutes_ago")             //%d分钟前
#define hours_ago                   LOLoadSourceString(2,@"hours_ago")               //%d小时前
#define within_15_minutes           LOLoadSourceString(2,@"within_15_minutes")       //15分钟内
#define within_1_hours              LOLoadSourceString(2,@"within_1_hours")          //1小时内
#define within_1_days               LOLoadSourceString(2,@"within_1_days")           //1天内
#define within_3_days               LOLoadSourceString(2,@"within_3_days")           //3天内
#define clear_and_logout            LOLoadSourceString(2,@"clear_and_logout")        //清除位置并退出
#define touch_scan                  LOLoadSourceString(2,@"touch_scan")              //轻触继续扫描
#define not_find_QR                 LOLoadSourceString(2,@"not_find_QR")             //未发现二维码
#define scan_explain                LOLoadSourceString(2,@"scan_explain")            //将二维码放入框即可自动扫描
#define send_card                   LOLoadSourceString(2,@"send_card")               //递名片
#define send_card_explain           LOLoadSourceString(2,@"send_card_explain")       //将名片滑出,递名片给附近好友
#define stop_search                 LOLoadSourceString(2,@"stop_search")             //停止搜索
#define no_body_explain             LOLoadSourceString(2,@"no_body_explain")         //啊哦,没有发现同时递名片的朋友
#define try_again                   LOLoadSourceString(2,@"try_again")               //点击再试一次吧
#define find_body_explain           LOLoadSourceString(2,@"find_body_explain")       //找到以下几张名片,点击加为好友吧
#define string_upload               LOLoadSourceString(2,@"string_upload")           //上传
#define string_merge                LOLoadSourceString(2,@"string_merge")            //合并
#define string_cover                LOLoadSourceString(2,@"string_cover")            //覆盖
#define synchronous_contact         LOLoadSourceString(2,@"synchronous_contact")     //同步联系人
#define synchronous_merge           LOLoadSourceString(2,@"synchronous_merge")       //同步合并中...
#define synchronous_explain         LOLoadSourceString(2,@"synchronous_explain")     //请确保已打开联系人权限,同步过程中请勿进行其他操作
#define upload_explain              LOLoadSourceString(2,@"upload_explain")          //确定上传您的联系人到卓越通讯录吗？
#define merge_explain               LOLoadSourceString(2,@"merge_explain")           //确定要将卓越通讯录联系人与手机合并吗？
#define cover_explain               LOLoadSourceString(2,@"cover_explain")           //确定要将卓越通讯录联系人覆盖到手机吗?本操作会删除手机原有联系人
#define upload_done                 LOLoadSourceString(2,@"upload_done")             //上传完成
#define uploading_addressbook       LOLoadSourceString(2,@"uploading_addressbook")   //通讯录上传中...
#define cover_done                  LOLoadSourceString(2,@"cover_done")              //覆盖完成
#define covering_addressbook        LOLoadSourceString(2,@"covering_addressbook")    //通讯录覆盖中...%d/%ld
#define merge_done                  LOLoadSourceString(2,@"merge_done")              //合并完成
#define merging_addressbook         LOLoadSourceString(2,@"merging_addressbook")     //通讯录合并中...%d/%ld
#define prevent_harass              LOLoadSourceString(2,@"prevent_harass")          //电话防骚扰
#define synchronous                 LOLoadSourceString(2,@"synchronous")             //同步中...
#define synchronous_count           LOLoadSourceString(2,@"synchronous_count")       //同步中...%ld/%ld
#define update_harass_library       LOLoadSourceString(2,@"update_harass_library")   //升级号码库,识别骚扰电话
#define harass_library_has_update   LOLoadSourceString(2,@"harass_library_has_update")//骚扰号码库有更新
#define has_new_version             LOLoadSourceString(2,@"has_new_version")         //有更新 %@
#define newest_version              LOLoadSourceString(2,@"newest_version")          //已是最新版本 %@
#define alert_close_harass1         LOLoadSourceString(2,@"alert_close_harass1")     //关闭骚扰功能
#define alert_close_harass2         LOLoadSourceString(2,@"alert_close_harass2")     //打开时需重新下载骚扰号码库
#define alert_open_harass1          LOLoadSourceString(2,@"alert_open_harass1")      //开启防骚扰功能
#define alert_open_harass2          LOLoadSourceString(2,@"alert_open_harass2")      //并下载骚扰号码库
#define conflict_contact            LOLoadSourceString(2,@"conflict_contact")        //冲突联系人
#define conflict_explain            LOLoadSourceString(2,@"conflict_explain")        //以下手机通讯录联系人,您备注了多个电话,这些电话指向了多个注册用户或卓越通讯录通讯录联系人,请手动匹配
#define safe_email                  LOLoadSourceString(2,@"safe_email")              //安全邮箱
#define repeat_contact              LOLoadSourceString(2,@"repeat_contact")          //重复联系人
#define contact_doctor              LOLoadSourceString(2,@"contact_doctor")          //通讯录医生
#define my_qr_code_card             LOLoadSourceString(2,@"my_qr_code_card")         //我的二维码名片
#define began_experience            LOLoadSourceString(2,@"began_experience")        //开始体检
#define my                          LOLoadSourceString(2,@"my")                      //我
#define had_bind_email              LOLoadSourceString(2,@"had_bind_email")          //已绑定
#define no_bind_email               LOLoadSourceString(2,@"no_bind_email")           //未绑定
#define had_bind                    LOLoadSourceString(2,@"had_bind")                //已绑定
#define no_conflict_contact         LOLoadSourceString(2,@"no_conflict_contact")     //无冲突联系人
#define had_conflict_contact        LOLoadSourceString(2,@"had_conflict_contact")    //有%@个冲突联系人
#define no_repeat_contact           LOLoadSourceString(2,@"no_repeat_contact")       //无重复联系人
#define had_repeat_contact          LOLoadSourceString(2,@"had_repeat_contact")      //有%@个重复联系人
#define selection_matching          LOLoadSourceString(2,@"selection_matching")      //选择匹配
#define matching_explain            LOLoadSourceString(2,@"matching_explain")        //确认匹配当前注册用户并同步到设备通讯录吗?
#define alert_first_check           LOLoadSourceString(2,@"alert_first_check")       //您还未进行通讯录体检\n是否现在体检？
#define now_check                   LOLoadSourceString(2,@"now_check")               //现在体检
#define alert_other_check           LOLoadSourceString(2,@"alert_other_check")       //您本次还未进行通讯录体检\n请体检后查看最新体检结果
#define alert_score_check           LOLoadSourceString(2,@"alert_score_check")       //上次体检结果%@分\n是否重新体检？
#define merge_info                  LOLoadSourceString(2,@"merge_info")              //合并信息
#define input_name                  LOLoadSourceString(2,@"input_name")              //请输入姓名
#define arranging                   LOLoadSourceString(2,@"arranging")               //整理中...
#define merge_header_explain        LOLoadSourceString(2,@"merge_header_explain")    //以下是您设备通讯录中可能重复的联系人,你可以手动进行合并,合并后旧数据会被删除
#define people_num                  LOLoadSourceString(2,@"people_num")              //%@人
#define had_find_people             LOLoadSourceString(2,@"had_find_people")         //已经找到%ld位好友
#define keep_search                 LOLoadSourceString(2,@"keep_search")             //继续搜索...
#define intercept_harassment        LOLoadSourceString(2,@"intercept_harassment")    //拦截骚扰电话
#define protect_account             LOLoadSourceString(2,@"protect_account")         //保障账号安全
#define arrangement_conflict        LOLoadSourceString(2,@"arrangement_conflict")    //使信息更准确
#define arrangement_repeat          LOLoadSourceString(2,@"arrangement_repeat")      //合并重复数据
#define has_open                    LOLoadSourceString(2,@"has_open")                //已开启
#define no_open                     LOLoadSourceString(2,@"no_open")                 //未开启
#define has_add_prevent_num         LOLoadSourceString(2,@"has_add_prevent_num")     //已识别%@个号码
#define has_handle_person           LOLoadSourceString(2,@"has_handle_person")       //已处理%@人
#define string_score                LOLoadSourceString(2,@"string_score")            //分
#define not_experience              LOLoadSourceString(2,@"not_experience")          //未体检
#define re_experience               LOLoadSourceString(2,@"re_experience")           //重新体检
#define health_score                LOLoadSourceString(2,@"health_score")            //健康评分
#define syn_upload_detail           LOLoadSourceString(2,@"syn_upload_detail")       //上传联系人至卓越通讯录进行储存备份
#define merge_addressbook           LOLoadSourceString(2,@"merge_addressbook")       //合并通讯录
#define syn_merge_detail            LOLoadSourceString(2,@"syn_merge_detail")        //下载卓越通讯录联系人数据与手机合并
#define cover_addressbook           LOLoadSourceString(2,@"cover_addressbook")       //覆盖通讯录
#define syn_cover_detail            LOLoadSourceString(2,@"syn_cover_detail")        //下载卓越通讯录联系人数据覆盖到手机
#define upload_before_count         LOLoadSourceString(2,@"upload_before_count")     //原卓越通讯录联系人%ld人
#define upload_now_count            LOLoadSourceString(2,@"upload_now_count")        //现卓越通讯录联系人%ld人
#define merge_cover_before_count    LOLoadSourceString(2,@"merge_cover_before_count")//原设备通讯录联系人%ld人
#define merge_cover_now_count       LOLoadSourceString(2,@"merge_cover_now_count")   //现设备通讯录联系人%ld人
#define last_upload_time            LOLoadSourceString(2,@"last_upload_time")        //最后上传时间:%@
#define last_merge_time             LOLoadSourceString(2,@"last_merge_time")         //最后合并时间:%@
#define last_cover_time             LOLoadSourceString(2,@"last_cover_time")         //最后覆盖时间:%@
#define discovery_circyle_nobody    LOLoadSourceString(2,@"discovery_circyle_nobody") //圈子中无好友

#define back_manage                 LOLoadSourceString(2,@"back_manage")             //备份管理
#define backup_tx                   LOLoadSourceString(2,@"backup_tx")               //备份提醒
#define backup_attl1                LOLoadSourceString(2,@"backup_attl1")            //每两周提醒您备份通讯录数据
#define backup_str                  LOLoadSourceString(2,@"backupstr")               //备份
#define backup_failed               LOLoadSourceString(2,@"backup_failed")           //备份失败
#define backup_resore               LOLoadSourceString(2,@"backup_resore")           //还原
#define backup_attl2                LOLoadSourceString(2,@"backup_attl2")            //将卓越通讯录联系人信息进行备份
#define backup_attl3                LOLoadSourceString(2,@"backup_attl3")            //将卓越通讯录联系人信息还原至备份时的状态
#define backup_frome_c              LOLoadSourceString(2,@"backup_frome_c")          //最后备份时间：[@]%@[$]\n当前联系人：[@]%@[$]     最后备份联系人：[@]%@[$]
#define backuping_str               LOLoadSourceString(2,@"backuping_str")           //备份中……
#define restoreing_str              LOLoadSourceString(2,@"restoreing_str")          //还原中……
#define backuping_frm               LOLoadSourceString(2,@"backuping_frm")           //您当前有%@个备份，最多可拥有%d个备份数据
#define backuping_count             LOLoadSourceString(2,@"backuping_count")         //最多可拥有%d个备份数据
#define bakcup_max_bl               LOLoadSourceString(2,@"bakcup_max_bl")           //您最多可拥有%d个备份，超过将只保留最近的%d个备份
#define backup_all_str              LOLoadSourceString(2,@"backup_all_str")          //备份数已满
#define backup_resum                LOLoadSourceString(2,@"backup_resum")            //继续备份
#define backup_now_cnt              LOLoadSourceString(2,@"backup_now_cnt")          //本次备份操作：备份联系人%@人
#define backup_success              LOLoadSourceString(2,@"backup_success")          //备份成功
#define restore_success             LOLoadSourceString(2,@"restore_success")         //还原成功
#define restrore_opercnt            LOLoadSourceString(2,@"restrore_opercnt")        //本次还原操作：还原联系人%lu人
#define restrore_op_ok              LOLoadSourceString(2,@"restrore_op_ok")          //确认进行还原操作?
#define restrore_contact_baok       LOLoadSourceString(2,@"restrore_contact_baok")   //您的联系人信息将还原至所选的备份时的状态
#define backup_time_str             LOLoadSourceString(2,@"backup_time_str")         //备份时间：%@
#define bakcup_conts_str            LOLoadSourceString(2,@"bakcup_conts_str")        //备份联系人：%@
#define backup_select               LOLoadSourceString(2,@"backup_select")           //选择备份
#define backup_ok_str               LOLoadSourceString(2,@"backup_ok_str")           //确定备份联系人信息?
#define detection                   LOLoadSourceString(2,@"detection")               //检测中
#define fail_qr_code                LOLoadSourceString(2,@"fail_qr_code")            //无效的二维码
#define upload_fail_no_contact      LOLoadSourceString(2,@"upload_fail_no_contact")  //上传失败，您的手机通讯录没有联系人
#define merge_fail_no_contact       LOLoadSourceString(2,@"merge_fail_no_contact")   //合并失败，您的卓越通讯录没有联系人
#define cover_fail_no_contact       LOLoadSourceString(2,@"cover_fail_no_contact")   //覆盖失败，您的卓越通讯录没有联系人

//3 我
#define my_dynamic                  LOLoadSourceString(3,@"my_dynamic")              //我的动态
#define my_visit                    LOLoadSourceString(3,@"my_visit")                //我的访客
#define privacy_setting             LOLoadSourceString(3,@"privacy_setting")         //隐私设置
#define more_setting                LOLoadSourceString(3,@"more_setting")            //更多设置
#define perfect_info                LOLoadSourceString(3,@"perfect_info")            //请完善您的资料
#define self_change_bind_tel        LOLoadSourceString(3,@"self_change_bind_tel")    //您更改了绑定电话
#define self_change_company         LOLoadSourceString(3,@"self_change_company")     //您修改了公司信息
#define self_change_position        LOLoadSourceString(3,@"self_change_position")    //您修改了职位信息
#define self_change_tel             LOLoadSourceString(3,@"self_change_tel")         //您修改了备注电话
#define self_change_birthday        LOLoadSourceString(3,@"self_change_birthday")    //您修改了生日
#define self_change_education       LOLoadSourceString(3,@"self_change_education")   //您修改了教育信息
#define account_safe                LOLoadSourceString(3,@"account_safe")            //账号与安全
#define mobile_number               LOLoadSourceString(3,@"mobile_number")           //手机号
#define binding_email               LOLoadSourceString(3,@"binding_email")           //绑定邮箱
#define binding_QQ                  LOLoadSourceString(3,@"binding_QQ")              //绑定QQ
#define binding_WeChat              LOLoadSourceString(3,@"binding_WeChat")          //绑定微信
#define binding_weibo               LOLoadSourceString(3,@"binding_weibo")           //绑定微博
#define change_password             LOLoadSourceString(3,@"change_password")         //修改登录密码
#define not_binding                 LOLoadSourceString(3,@"not_binding")             //未绑定
#define input_new_binding_tel       LOLoadSourceString(3,@"input_new_binding_tel")   //填写新的绑定手机号
#define change_bind_email           LOLoadSourceString(3,@"change_bind_email")       //更换绑定邮箱
#define alert_input_email           LOLoadSourceString(3,@"alert_input_email")       //请输入邮箱地址
#define binding_email_explain       LOLoadSourceString(3,@"binding_email_explain")   //你可以使用已验证过的邮箱地址登录卓越通讯录,也可以用它来找回卓越通讯录登录密码
#define alert_new_email_equal       LOLoadSourceString(3,@"alert_new_email_equal")   //输入的邮箱地址与原地址相同,请重新输入
#define string_binding_tel          LOLoadSourceString(3,@"string_binding_tel")      //绑定手机号
#define your_tel_number             LOLoadSourceString(3,@"your_tel_number")         //你的手机号:%@
#define change_tel_number           LOLoadSourceString(3,@"change_tel_number")       //更换手机号
#define change_zhuoyue_password     LOLoadSourceString(3,@"change_zhuoyue_password") //更改卓越通讯录密码
#define old_new_password_equal      LOLoadSourceString(3,@"old_new_password_equal")  //新密码与旧密码相同
#define new_password_not_equal      LOLoadSourceString(3,@"new_password_not_equal")  //密码输入不一致
#define new_password_range          LOLoadSourceString(3,@"new_password_range")      //新密码需要6-14位!
#define password_change_success     LOLoadSourceString(3,@"password_change_success") //密码修改成功
#define set_password                LOLoadSourceString(3,@"set_password")            //设置密码
#define set_password_explain        LOLoadSourceString(3,@"set_password_explain")    //请填写你以后的登录密码
#define string_password             LOLoadSourceString(3,@"string_password")         //密码
#define string_confirm_password     LOLoadSourceString(3,@"string_confirm_password") //确认密码
#define password_explain            LOLoadSourceString(3,@"password_explain")        //设置6-14位密码
#define input_password_again        LOLoadSourceString(3,@"input_password_again")    //再次输入密码
#define input_identifying_code      LOLoadSourceString(3,@"input_identifying_code")  //输入验证码
#define alert_send_code_to_tel      LOLoadSourceString(3,@"alert_send_code_to_tel")  //我们已发送验证码短信到这个号码
#define alert_send_code_to_email    LOLoadSourceString(3,@"alert_send_code_to_email")//我们已发送验证码到这个邮箱
#define please_input_code           LOLoadSourceString(3,@"please_input_code")       //请输入验证码
#define reget_code                  LOLoadSourceString(3,@"reget_code")              //(%ld) 重新获取验证码
#define string_submit               LOLoadSourceString(3,@"string_submit")           //提交
#define change_bind_success         LOLoadSourceString(3,@"change_bind_success")     //更改绑定成功
#define feed_back                   LOLoadSourceString(3,@"feed_back")               //用户反馈
#define feed_back_explain           LOLoadSourceString(3,@"feed_back_explain")       //使用中遇到问题,可以在此提交,我们收到后会尽快处理
#define feed_not_empty              LOLoadSourceString(3,@"feed_not_empty")          //反馈内容不能为容
#define feed_success                LOLoadSourceString(3,@"feed_success")            //反馈提交成功
#define outnumber                   LOLoadSourceString(3,@"outnumber")               //超过%d
#define news_setting                LOLoadSourceString(3,@"news_setting")            //新消息通知
#define give_praise                 LOLoadSourceString(3,@"give_praise")             //给我好评
#define about                       LOLoadSourceString(3,@"about")                   //关于
#define str_logout                  LOLoadSourceString(3,@"logout")                  //退出登录
#define alert_logout                LOLoadSourceString(3,@"alert_logout")            //确定退出卓越通讯录?
#define about_explain               LOLoadSourceString(3,@"about_explain")           //扫描二维码,您的朋友就能下载使用%@
#define function_explain            LOLoadSourceString(3,@"function_explain")        //功能介绍
#define edit_something              LOLoadSourceString(3,@"edit_something")          //修改%@
#define add_something               LOLoadSourceString(3,@"add_something")           //新增%@
#define must_input                  LOLoadSourceString(3,@"must_input")              //必填
#define must_select                 LOLoadSourceString(3,@"must_select")             //必选
#define string_area                 LOLoadSourceString(3,@"string_area")             //地区
#define not_support_location        LOLoadSourceString(3,@"not_support_location")    //该设备不支持定位服务
#define location_not_open           LOLoadSourceString(3,@"location_not_open")       //定位服务未开启
#define had_select_area             LOLoadSourceString(3,@"had_select_area")         //已选地区
#define position_to_position        LOLoadSourceString(3,@"position_to_position")    //定位到的位置
#define string_all                  LOLoadSourceString(3,@"string_all")              //全部
#define group_edit_input            LOLoadSourceString(3,@"group_edit_input")        //群名称
#define string_address              LOLoadSourceString(3,@"string_address")          //地址
#define string_school               LOLoadSourceString(3,@"string_school")           //学校
#define string_professional         LOLoadSourceString(3,@"string_professional")     //专业
#define edit_remak                  LOLoadSourceString(3,@"edit_remak")              //编辑备忘
#define remark_email                LOLoadSourceString(3,@"remark_email")            //备注邮箱
#define request_send                LOLoadSourceString(3,@"request_send")            //发送申请
#define send_add_friend_string      LOLoadSourceString(3,@"send_add_friend_string")  //换个名片,认识一下吧!
#define send_add_explain            LOLoadSourceString(3,@"send_add_explain")        //您需要发送验证申请,等待对方通过
#define string_can_not_input_out    LOLoadSourceString(3,@"string_can_not_input_out")//%@不能超过%d位
#define name_can_not_input_out      LOLoadSourceString(3,@"name_can_not_input_out")  //%@不能超过%ld位
#define content_not_change          LOLoadSourceString(3,@"content_not_change")      //内容没有被修改
#define name_can_not_contain        LOLoadSourceString(3,@"name_can_not_contain")    //不能同时包含汉字和字母
#define email_format_illegal        LOLoadSourceString(3,@"email_format_illegal")    //邮箱格式不合法
#define mutst_in_number             LOLoadSourceString(3,@"mutst_in_number")         //%@必须为不超过%ld位的纯数字
#define content_not_empty           LOLoadSourceString(3,@"content_not_empty")       //内容不能为空
#define name_only_is                LOLoadSourceString(3,@"name_only_is")            //姓名不能同时包含汉字和字母
#define live_info                   LOLoadSourceString(3,@"live_info")               //背景资料
#define new_work_experience         LOLoadSourceString(3,@"new_work_experience")     //新增工作经历
#define new_education_experience    LOLoadSourceString(3,@"new_education_experience")//新增教育经历
#define work_experience             LOLoadSourceString(3,@"work_experience")         //工作经历
#define education_experience        LOLoadSourceString(3,@"education_experience")    //教育经历
#define alert_del_experience        LOLoadSourceString(3,@"alert_del_experience")    //是否删除本条经历
#define alert_work_experience_max   LOLoadSourceString(3,@"alert_work_experience_max")//工作经历最多只能录入%ld个
#define alert_edu_experience_max    LOLoadSourceString(3,@"alert_edu_experience_max")//教育经历最多只能录入%ld个
#define manage_label                LOLoadSourceString(3,@"manage_label")            //管理标签
#define create_label                LOLoadSourceString(3,@"create_label")            //创建了标签
#define click_label                 LOLoadSourceString(3,@"click_label")             //认可了你的标签
#define alert_select_click          LOLoadSourceString(3,@"alert_select_click")      //选中标签进行删除,最多一次选择%d个
#define alert_del_label             LOLoadSourceString(3,@"alert_del_label")         //当前有%ld个白色的标签将会被删除,您确定吗?
#define to_be_perfect               LOLoadSourceString(3,@"to_be_perfect")           //待完善
#define to_be_required              LOLoadSourceString(3,@"to_be_required")         //必填
#define my_info                     LOLoadSourceString(3,@"my_info")                 //我的资料
#define my_QR_code                  LOLoadSourceString(3,@"my_QR_code")              //我的二维码
#define tel_list                    LOLoadSourceString(3,@"tel_list")                //电话列表
#define remark_new_tel              LOLoadSourceString(3,@"remark_new_tel")          //备注新的电话
#define register_tel                LOLoadSourceString(3,@"register_tel")            //注册号码
#define my_remark_tel               LOLoadSourceString(3,@"my_remark_tel")           //我备注的号码
#define select_work_experience      LOLoadSourceString(3,@"select_work_experience")  //选择工作经历
#define string_voice                LOLoadSourceString(3,@"string_voice")            //声音
#define string_vibrate              LOLoadSourceString(3,@"string_vibrate")          //震动
#define news_setting_explain        LOLoadSourceString(3,@"news_setting_explain")    //当卓越通讯录有新消息时,你可以设置是否需要声音或震动
#define set_group_authority         LOLoadSourceString(3,@"set_group_authority")     //设置分组权限
#define this_group_can_see_live     LOLoadSourceString(3,@"this_group_can_see_live") //这些组可以查看我的背景
#define my_group                    LOLoadSourceString(3,@"my_group")                //我的分组
#define my_QR_code_explain          LOLoadSourceString(3,@"my_QR_code_explain")      //扫一扫上面的二维码图案,加我名片
#define string_header               LOLoadSourceString(3,@"string_header")           //头像
#define contact_info                LOLoadSourceString(3,@"contact_info")            //联系方式
#define live_change                 LOLoadSourceString(3,@"live_change")             //背景修改
#define check_update                LOLoadSourceString(3,@"check_update")            //检查更新
#define string_time                 LOLoadSourceString(3,@"string_time")             //时间
#define string_education            LOLoadSourceString(3,@"string_education")        //学历
#define string_profession           LOLoadSourceString(3,@"string_profession")       //院系/专业
#define time_in_school              LOLoadSourceString(3,@"time_in_school")          //在校时间
#define equal_edu                   LOLoadSourceString(3,@"equal_edu")               //教育经历重复
#define equal_job                   LOLoadSourceString(3,@"equal_job")               //工作经历重复
#define feed_input_out_max          LOLoadSourceString(3,@"feed_input_out_max")      //用户反馈超过了最大限制
#define can_change                  LOLoadSourceString(3,@"can_change")              //[可更换]
#define recom_use                   LOLoadSourceString(3,@"recom_use")               //推荐使用
#define select_live                 LOLoadSourceString(3,@"select_live")             //选择背景资料
#define alert_change_bind_tel       LOLoadSourceString(3,@"alert_change_bind_tel")   //更换流程：\n 1.点击更换手机号码\n 2.输入手机号码，获取验证码\n 3.填写验证码提交验证，绑定成功
#define merge_use_other_header      LOLoadSourceString(3,@"merge_use_other_header")  //使用另外一个重复联系人的头像
#define no_conflict_text            LOLoadSourceString(3,@"no_conflict_text")        //您的通讯录很健康，没有冲突的联系人
#define no_repeat_text              LOLoadSourceString(3,@"no_repeat_text")          //您的通讯录很健康，没有重复的联系人
#define no_morethan_30              LOLoadSourceString(3,@"no_morethan_30")          //%@不能超过20个字符
#define info_score_1                LOLoadSourceString(3,@"info_score_1")            //资料完善度%@,暂时不能查看好友更多资料
#define info_score_2                LOLoadSourceString(3,@"info_score_2")            //资料完善度%@,您的信息越完善,将能为你找到更多好友
#define info_score_3                LOLoadSourceString(3,@"info_score_3")            //恭喜你,您的资料完善度达到了%@
#define string_comAddres            LOLoadSourceString(3,@"string_comAddres")    //公司网址
#define string_comFax               LOLoadSourceString(3,@"string_comFax")          //公司传真

//4 公用
#define STR_MESSAGE                 LOLoadSourceString(4,@"message")
#define STR_MY                      LOLoadSourceString(4,@"myself")
#define STR_DISCOVER                LOLoadSourceString(4,@"discover")
#define STR_CONTACT                 LOLoadSourceString(4,@"contact")
#define courtry_location            LOLoadSourceString(4,@"couttyr")                //国家和地区
#define cour_china                  LOLoadSourceString(4,@"china")                  //中国
#define input_tel_card              LOLoadSourceString(4,@"inputtelcard")
#define please_input_nameAndTel     LOLoadSourceString(4,@"inputnametel")
#define sel_marching                LOLoadSourceString(4,@"selmarch")               //选择匹配
#define sel_Merger                  LOLoadSourceString(4,@"selmerger")              //选择合并
#define clear_chat_record           LOLoadSourceString(4,@"clear_char")
#define discover_not_persion        LOLoadSourceString(4,@"not_persion")
#define contact_empty_p             LOLoadSourceString(4,@"emtty_p")
#define cir_not_add                 LOLoadSourceString(4,@"cir_not_add")
#define date_y_m_d                  LOLoadSourceString(4,@"date_y_m_d")             //yyyy年MM月dd
#define date_h_m                    LOLoadSourceString(4,@"date_h_m")               //hh:mm
#define date_m_h_m                  LOLoadSourceString(4,@"date_m_h_m")             //MM月dd hh:mm
#define button_cancel               LOLoadSourceString(4,@"cancel")                 //取消
#define button_remind               LOLoadSourceString(4,@"remind")                 //提醒
#define button_ok                   LOLoadSourceString(4,@"ok")                     //确定
#define button_new                  LOLoadSourceString(4,@"new")                    //新建
#define button_del                  LOLoadSourceString(4,@"button_del")             //删除
#define button_add                  LOLoadSourceString(4,@"button_add")             //添加
#define button_change               LOLoadSourceString(4,@"button_change")          //修改
#define button_back                 LOLoadSourceString(4,@"button_back")            //返回
#define button_save                 LOLoadSourceString(4,@"button_save")            //保存
#define alert_location              LOLoadSourceString(4,@"alert_location")         //设备没有开启定位服务,请到设置->定位中开启
#define string_today                LOLoadSourceString(4,@"today")                  //今天
#define string_yesterday            LOLoadSourceString(4,@"yesterday")              //昨天
#define string_tomorrow             LOLoadSourceString(4,@"tomorrow")               //明天
#define to_this_day                 LOLoadSourceString(4,@"to_this_day")            //至今
#define years_ago                   LOLoadSourceString(4,@"years_ago")              //%d年前
#define months_ago                  LOLoadSourceString(4,@"months_ago")             //%d个月前
#define days_ago                    LOLoadSourceString(4,@"days_ago")               //%d天前
#define string_phone                LOLoadSourceString(4,@"phone")                  //手机
#define string_share                LOLoadSourceString(4,@"share")                  //分享
#define telephone                   LOLoadSourceString(4,@"telephone")              //电话
#define string_email                LOLoadSourceString(4,@"email")                  //邮箱
#define weixin_friend               LOLoadSourceString(4,@"weixin_friend")          //微信好友
#define string_message              LOLoadSourceString(4,@"string_message")         //短信
#define zhuoyue_friend              LOLoadSourceString(4,@"zhuoyue_friend")         //卓越好友
#define string_name                 LOLoadSourceString(4,@"string_name")            //姓名
#define string_company              LOLoadSourceString(4,@"string_company")         //公司
#define string_position             LOLoadSourceString(4,@"string_position")        //职位
#define string_camera               LOLoadSourceString(4,@"string_camera")          //拍照
#define string_by_photo             LOLoadSourceString(4,@"string_by_photo")        //从手机相册中选择
#define uploading                   LOLoadSourceString(4,@"uploading")              //正在上传...
#define save_photo                  LOLoadSourceString(4,@"save_photo")             //保存图片
#define send_to_firend              LOLoadSourceString(4,@"send_to_firend")         //发送给朋友
#define string_weixin               LOLoadSourceString(4,@"string_weixin")          //微信
#define change_header               LOLoadSourceString(4,@"change_header")          //更换头像
#define string_label                LOLoadSourceString(4,@"string_label")           //标签
#define string_live                 LOLoadSourceString(4,@"string_live")            //背景
#define string_remark               LOLoadSourceString(4,@"string_remark")          //备忘
#define invite_message              LOLoadSourceString(4,@"invite_message")         //嗨,%@,跟我们一起来用卓越通讯录吧!联系你们特别方便~
#define save_this_edit              LOLoadSourceString(4,@"save_this_edit")         //是否保存本次编辑
#define button_not_save             LOLoadSourceString(4,@"button_not_save")        //不保存
#define tel_number                  LOLoadSourceString(4,@"tel_number")             //电话号码
#define string_done                 LOLoadSourceString(4,@"string_done")            //完成
#define alert_input_tel             LOLoadSourceString(4,@"alert_input_tel")        //请输入手机号
#define content_empty               LOLoadSourceString(4,@"content_empty")          //目前还没有内容哟
#define search_no_empty             LOLoadSourceString(4,@"search_no_empty")        //搜索无结果
#define string_loading              LOLoadSourceString(4,@"loading")                //加载中...
#define string_photo                LOLoadSourceString(4,@"string_photo")           //相册
#define button_close                LOLoadSourceString(4,@"button_close")           //关闭
#define about_secret_desc           LOLoadSourceString(4,@"about_secret_desc")       //隐私说明
#define serve_explain               LOLoadSourceString(4,@"serve_explain")          //服务协议及隐私说明
#define master_index                LOLoadSourceString(4,@"master_index")           //达人指数
#define share_by                    LOLoadSourceString(4,@"share_by")               //通过以下方式分享
#define circle_of_friends           LOLoadSourceString(4,@"circle_of_friends")      //朋友圈
#define master_share_explain        LOLoadSourceString(4,@"master_share_explain")   //真实姓名,真实号码,我们只提供真正的好友信息
#define simulatr_not_supported      LOLoadSourceString(4,@"simulatr_not_supported") //模拟器不支持
#define string_good                 LOLoadSourceString(4,@"string_good")            //好
#define save_failed                 LOLoadSourceString(4,@"save_failed")            //保存失败
#define save_success                LOLoadSourceString(4,@"save_success")           //保存成功
#define string_sex                  LOLoadSourceString(4,@"string_sex")             //性别
#define string_man                  LOLoadSourceString(4,@"string_man")             //男
#define string_woman                LOLoadSourceString(4,@"string_woman")           //女
#define string_call                 LOLoadSourceString(4,@"string_call")            //拨打
#define no_name                     LOLoadSourceString(4,@"no_name")                //(无姓名)
#define no_tel                      LOLoadSourceString(4,@"no_tel")                 //(无号码)
#define now_loading                 LOLoadSourceString(4,@"now_loading")            //正在加载
#define show_years                  LOLoadSourceString(4,@"show_years")             //显示年份
#define ignore_years                LOLoadSourceString(4,@"ignore_years")           //忽略年份
#define str_lunar_calendar          LOLoadSourceString(4,@"str_lunar_calendar")     //农历
#define str_gregorian_calendar      LOLoadSourceString(4,@"str_gregorian_calendar") //公历
#define no_find_network             LOLoadSourceString(4,@"no_find_network")        //未能连接到互联网
#define network_explain1            LOLoadSourceString(4,@"network_explain1")       //您的设备未启用移动网络或Wi-Fi网络
#define network_explain2            LOLoadSourceString(4,@"network_explain2")       //如需要连接到互联网，可以参考以下几点：
#define network_explain2_1          LOLoadSourceString(4,@"network_explain2_1")     //检查手机中的无线局域网设置，查看是否有可接入的无线局域网信号。
#define network_explain2_2          LOLoadSourceString(4,@"network_explain2_2")     //检查手机是否已接入移动网络，并且手机没有被停机。
#define network_explain3            LOLoadSourceString(4,@"network_explain3")       //如果您已接入无线局域网：
#define network_explain3_1          LOLoadSourceString(4,@"network_explain3_1")     //请检查您所连接的无线局域网热点是否已接入互联网，或该热点是否已允许您的设备访问互联网。
#define network_title               LOLoadSourceString(4,@"network_title")          //网络无法连接
#define down_failed                 LOLoadSourceString(4,@"down_failed")            //下载失败
#define max_remark_tel_num          LOLoadSourceString(4,@"max_remark_tel_num")     //您最多可为此联系人备注%@个号码
#define min_remark_tel_num          LOLoadSourceString(4,@"min_remark_tel_num")     //联系人至少需要有一个电话号码
#define upload_failed               LOLoadSourceString(4,@"upload_failed")          //上传失败
#define app_down_string             LOLoadSourceString(4,@"app_down_string")        //%@的下载地址:%@
#define net_NotReachable            LOLoadSourceString(4,@"net_NotReachable")        //未连接
#define network_timeout             LOLoadSourceString(4,@"network_timeout")        //连接超时，请检查您的网络
#define wxIsNotInstall              LOLoadSourceString(4,@"wxIsNotInstall")         //尚未安装微信客户端!无法进行授权!
#define changeName_toast              LOLoadSourceString(4,@"changeName_toast")     //每30天内可修改一次姓名


#pragma mark - ------------- 5 登录注册------------------
#define register_by_mobile          LOLoadSourceString(5,@"register_by_mobile")      //使用手机号码注册
#define register_explain            LOLoadSourceString(5,@"register_explain")        //为了给您提供更加真实准确的服务，以方便您找到失联已久的朋友，所以我们需要获取您的真实号码和真实姓名。
#define register_explain1           LOLoadSourceString(5,@"register_explain1")       //一经注册则代表您已同意
#define app_clause                  LOLoadSourceString(5,@"app_clause")              //《卓越通讯录服务协议及隐私说明》
#define input_tel_by_get_code       LOLoadSourceString(5,@"input_tel_by_get_code")   //请输入手机号获取验证码
#define get_code                    LOLoadSourceString(5,@"get_code")                //获取验证码
#define alert_new_tel_equal         LOLoadSourceString(5,@"alert_new_tel_equal")     //输入的新手机号码与原号码相同,请重新输入
#define alert_send_code             LOLoadSourceString(5,@"alert_send_code")         //我们将发送验证码信息到这个号码:
#define confirm_tel                 LOLoadSourceString(5,@"confirm_tel")             //确认手机号码
#define string_login                LOLoadSourceString(5,@"string_login")            //登录
#define string_register             LOLoadSourceString(5,@"string_register")         //注册
#define input_name_title            LOLoadSourceString(5,@"input_name_title")        //填写姓名
#define upload_header               LOLoadSourceString(5,@"upload_header")           //上传头像
#define name_limit                  LOLoadSourceString(5,@"name_limit")              //请填写%ld-%ld个汉字
#define input_true_name             LOLoadSourceString(5,@"input_true_name")         //请填写真实姓名
#define input_name_explain1         LOLoadSourceString(5,@"input_name_explain1")     //真实姓名,真实号码,我们只提供真正的好友信息
#define input_name_explain2         LOLoadSourceString(5,@"input_name_explain2")     //请务必使用真实姓名注册,以方便快速找到你的好友
#define true_name                   LOLoadSourceString(5,@"true_name")               //真实姓名
#define string_next                 LOLoadSourceString(5,@"string_next")             //下一步
#define select_sex                  LOLoadSourceString(5,@"select_sex")              //请选择性别
#define name_is_only                LOLoadSourceString(5,@"name_is_only")            //姓名只能是汉字
#define alert_submit_name           LOLoadSourceString(5,@"alert_submit_name")       //真实姓名和性别提交后不可修改,请谨慎填写
#define login_by_email              LOLoadSourceString(5,@"login_by_email")          //使用邮箱登录
#define input_account               LOLoadSourceString(5,@"input_account")           //请填写账号
#define input_password              LOLoadSourceString(5,@"input_password")          //请填写密码
#define login_encounter_problem     LOLoadSourceString(5,@"login_encounter_problem") //登录遇到问题?
#define get_back_by_tel             LOLoadSourceString(5,@"get_back_by_tel")         //通过手机短信找回密码
#define get_back_by_email           LOLoadSourceString(5,@"get_back_by_email")       //通过安全邮箱找回密码
#define use_back_by_tel             LOLoadSourceString(5,@"use_back_by_tel")         //使用手机短信找回密码
#define use_back_by_email           LOLoadSourceString(5,@"use_back_by_email")       //使用安全邮箱找回密码
#define login_by_tel                LOLoadSourceString(5,@"login_by_tel")            //输入账号登录
#define login_to_email              LOLoadSourceString(5,@"login_to_email")          //改用邮箱登录
#define change_account              LOLoadSourceString(5,@"change_account")          //切换账号
#define input_tel_number            LOLoadSourceString(5,@"input_tel_number")        //请填写手机号码
#define input_email                 LOLoadSourceString(5,@"input_email")             //请填写安全邮箱
#define select_country              LOLoadSourceString(5,@"select_country")          //选择国家
#define upload_addressbook          LOLoadSourceString(5,@"upload_addressbook")      //上传通讯录
#define upload_register_explain1    LOLoadSourceString(5,@"upload_register_explain1")//将给你带来更多的好友,请确保已打开联系人权限
#define upload_register_explain2    LOLoadSourceString(5,@"upload_register_explain2")//上传通讯录仅用于计算好友关系并严格保密
#define import_now                  LOLoadSourceString(5,@"import_now")              //立即导入
#define processing                  LOLoadSourceString(5,@"processing")              //正在处理...(%d/%ld)
#define synchronous_done            LOLoadSourceString(5,@"synchronous_done")        //同步完成
#define login_chat_fail             LOLoadSourceString(5,@"login_chat_fail")         //聊天登录失败,是否重新登录
#define had_send_to                 LOLoadSourceString(5,@"had_send_to")             //验证码已发送到指定
#define input_new_password          LOLoadSourceString(5,@"input_new_password")      //请填写新密码%ld-%ld位
#define login_state_lose            LOLoadSourceString(5,@"login_state_lose")        //登录状态已失效,请重新登录
#define logining                    LOLoadSourceString(5,@"logining")                //登录中...
#define view_moring                 LOLoadSourceString(5,@"view_moring")             //查看更多
#define please_set_bir              LOLoadSourceString(5,@"please_set_bir")          //请先设置生日!
#define please_set_time             LOLoadSourceString(5,@"please_set_time")         //请先设置提醒时间!
#define quick_regist_third          LOLoadSourceString(5,@"quick_regist_third")      //社交账号快速注册
#define quick_login_third           LOLoadSourceString(5,@"quick_login_third")       //社交账号快速登录
#define upload_first_alert          LOLoadSourceString(5,@"upload_first_alert")      //首次帮您整理通讯录，您的联系人比较多\n需要一点时间，请耐心等待
#define string_middle               LOLoadSourceString(5,@"string_middle")           //中
#define account_placeHolder         LOLoadSourceString(5,@"account_placeHolder")     //手机号码/邮箱地址
#define registerAccount             LOLoadSourceString(5,@"registerAccount")         //注册帐号

#endif
